#!/usr/bin/env node
import { createHash } from 'node:crypto'
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const sourcePath = join(here, 'payload-src', 'installer.sh')
const installPath = join(here, 'install.sh')
const eggPath = join(here, 'egg-airi-factorio-server.json')
const LEGACY_SOURCE_PIN = '78ef2acf788189981d82aa9e15e9c33b3dedb29c'
const PAYLOAD_REF = 'b93cbd094a91508883f39450420fbb1caf6c3752'

function sha256(bytes) {
  return createHash('sha256').update(bytes).digest('hex')
}

function assertNpcV8Source(source) {
  const text = source.toString('utf8')
  const failures = []
  if (!text.includes('airi-deploy-v8')) failures.push('missing v8 deployment revision')
  if (!text.includes('AIRI_ACTOR_MODE')) failures.push('missing AIRI_ACTOR_MODE')
  if (!text.includes('AIRI_CHAT_PLAYER')) failures.push('missing AIRI_CHAT_PLAYER')
  if (!/AIRI_REF="[a-f0-9]{40}"/.test(text)) failures.push('missing immutable AIRI_REF pin')
  if (text.includes('airi-deploy-v7')) failures.push('contains v7 deployment guard')
  if (text.includes('explicit-authorized-single-connected-player')) failures.push('contains connected-player patch contract')
  if (text.includes(`AIRI_REF="${LEGACY_SOURCE_PIN}"`)) failures.push('pins the legacy connected-player source')
  if (text.includes('operationCommands')) failures.push('contains legacy operationCommands model contract')
  if (failures.length) throw new Error(`Refusing to generate v8 artifacts: ${failures.join('; ')}`)
}

export function installerLoader(source) {
  assertNpcV8Source(source)
  const sourceHash = sha256(source)
  return `#!/usr/bin/env bash
# Generated AIRI Factorio swarm-capable standalone-NPC v8 installer loader.
# Immutable source: deploy/pterodactyl/payload-src/installer.sh
set -Eeuo pipefail
umask 077
REF="${PAYLOAD_REF}"
EXPECTED_SOURCE_SHA256="${sourceHash}"
URL="https://raw.githubusercontent.com/TTLouis/airi-factorio/$REF/deploy/pterodactyl/payload-src/installer.sh"
TMP="$(mktemp)"
log() { printf '[AIRI bootstrap] %s\\n' "$*"; }
fail() { log "ERROR: $*" >&2; exit 78; }
cleanup() { local code=$?; trap - EXIT; rm -f -- "$TMP"; exit "$code"; }
trap cleanup EXIT
trap 'exit 130' INT
trap 'exit 143' TERM HUP
for tool in bash curl sha256sum awk mktemp rm; do command -v "$tool" >/dev/null || fail "Missing installer loader tool: $tool"; done
curl --fail --location --retry 8 --retry-delay 5 --retry-max-time 240 --retry-all-errors --connect-timeout 20 --max-time 900 --proto '=https' --proto-redir '=https' "$URL" --output "$TMP" || fail 'Unable to download pinned AIRI installer source'
ACTUAL_SOURCE_SHA256="$(sha256sum "$TMP" | awk '{print $1}')"
[[ "$ACTUAL_SOURCE_SHA256" == "$EXPECTED_SOURCE_SHA256" ]] || fail 'Pinned AIRI installer source checksum mismatch'
if [[ "\${1:-}" == '--verify-only' ]]; then log "Pinned payload verified at $REF; installation was not run."; exit 0; fi
[[ $# == 0 ]] || fail 'Only --verify-only is supported as a loader argument.'
log "Using immutable installer payload $REF"
bash "$TMP"
`
}

function variable(name, description, envVariable, defaultValue, rules, { viewable = true } = {}) {
  return {
    name,
    description,
    env_variable: envVariable,
    default_value: defaultValue,
    user_viewable: viewable,
    user_editable: true,
    rules,
    field_type: 'text',
  }
}

function egg(installScript) {
  return {
    _comment: 'DO NOT EDIT: generated by deploy/pterodactyl/build-payload.mjs',
    meta: { version: 'PTDL_v2', update_url: null },
    exported_at: '2026-09-14T00:00:00+00:00',
    name: 'AIRI Factorio Server (Swarm-Capable NPC v8)',
    author: 'noreply@ttlouis.space',
    description: 'Swarm-capable AIRI Factorio preview. Installs the validated multi-NPC Autorio runtime and hardened v8 supervisor. The bundled chat/LLM loop remains single-NPC while swarm Blackboard coordination APIs are staged for rollout. Loopback-only RCON is managed by the supervisor.',
    features: [],
    docker_images: {
      'ghcr.io/ptero-eggs/yolks:debian_bookworm': 'ghcr.io/ptero-eggs/yolks:debian_bookworm',
    },
    file_denylist: [],
    startup: 'bash ./start-airi.sh',
    config: {
      files: '{}',
      startup: '{"done": "AIRI Factorio ready"}',
      logs: '{}',
      stop: '^C',
    },
    scripts: {
      installation: {
        script: installScript,
        container: 'ghcr.io/ptero-eggs/yolks:debian_bookworm',
        entrypoint: 'bash',
      },
    },
    variables: [
      variable('AIRI Actor Mode', 'Controlled actor mode. The v8 egg currently starts the chat supervisor on one standalone NPC while the installed Autorio mod is swarm-capable.', 'AIRI_ACTOR_MODE', 'npc', 'required|string|in:npc'),
      variable('AIRI Chat Player', 'Optional exact in-game player name allowed to issue !airi chat requests. This does not control that player character.', 'AIRI_CHAT_PLAYER', '', 'nullable|string|max:64'),
      variable('OpenAI API Key', 'Provider credential. Kept environment-only and never written to airi-config.json.', 'OPENAI_API_KEY', '', 'required|string|max:512', { viewable: false }),
      variable('AI Model', 'OpenAI-compatible model identifier used by AIRI.', 'OPENAI_MODEL', 'gpt-5.6', 'required|string|max:200'),
      variable('Provider Base URL', 'OpenAI-compatible API base URL. Remote endpoints must use HTTPS.', 'OPENAI_API_BASEURL', 'https://api.openai.com/v1', 'required|string|url|max:255'),
      variable('Save File Name', 'Save under /saves. Leave blank to use the newest existing save or create airi-world.zip.', 'SAVE_NAME', '', 'nullable|string|max:160'),
      variable('Max AI Requests Per Hour', 'Persisted hourly provider request cap.', 'MAX_PROVIDER_REQUESTS_PER_HOUR', '30', 'required|numeric|between:1,1200'),
      variable('Shutdown Timeout (ms)', 'Graceful Factorio save/stop timeout before forced termination.', 'SHUTDOWN_TIMEOUT_MS', '60000', 'required|numeric|between:1000,300000'),
      variable('Factorio Version', 'Factorio 2.0 headless version: latest, experimental, or exact 2.0.x.', 'FACTORIO_VERSION', 'latest', 'required|string|max:20'),
    ],
  }
}

export function buildArtifacts(source) {
  const installScript = installerLoader(source)
  const eggJson = `${JSON.stringify(egg(installScript), null, 4)}\n`
  return { installScript, eggJson }
}

function normalizeCheckoutText(text) {
  return text.replaceAll('\r\n', '\n')
}

export function verifyGeneratedArtifacts(source, installText, eggText) {
  assertNpcV8Source(source)
  const currentInstall = normalizeCheckoutText(installText)
  const currentEgg = normalizeCheckoutText(eggText)
  const expected = buildArtifacts(source)
  if (currentInstall !== expected.installScript) throw new Error('Generated install.sh loader is stale')
  let parsedEgg
  try { parsedEgg = JSON.parse(currentEgg) }
  catch (error) { throw new Error(`Generated egg JSON is invalid: ${error.message}`) }
  if (normalizeCheckoutText(parsedEgg?.scripts?.installation?.script ?? '') !== expected.installScript) {
    throw new Error('Generated egg does not embed the expected immutable installer loader')
  }
  if (currentEgg !== expected.eggJson) throw new Error('Generated egg schema is stale')
  return true
}

function main() {
  const checkOnly = process.argv.includes('--check')
  if (process.argv.length > 3 || (process.argv.length === 3 && !checkOnly)) throw new Error('Usage: node build-payload.mjs [--check]')
  const source = readFileSync(sourcePath)
  if (checkOnly) {
    verifyGeneratedArtifacts(source, readFileSync(installPath, 'utf8'), readFileSync(eggPath, 'utf8'))
    console.log('Pterodactyl swarm-capable v8 artifacts are current and internally verified.')
    return
  }
  const { installScript, eggJson } = buildArtifacts(source)
  writeFileSync(installPath, installScript)
  writeFileSync(eggPath, eggJson)
  console.log('Generated swarm-capable v8 install.sh and egg-airi-factorio-server.json.')
  console.log(`  payload source sha256: ${sha256(source)}`)
  console.log(`  immutable payload ref: ${PAYLOAD_REF}`)
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) main()
